name: Build On PR

on:
  pull_request:
    branches: ["master"]
  merge_group:

permissions:
  contents: read

jobs:
  build-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore BopVisualEffects.sln -p:SkipGameReferences=true

      - name: Build
        run: dotnet build BopVisualEffects.sln -c Release -p:SkipGameReferences=true --no-restore
