name: Format And Code Style

on:
  pull_request:
    branches: ["master"]
  merge_group:

permissions:
  contents: read

jobs:
  setup-game-dlls:
    uses: ./.github/workflows/setup-game-dlls.yml
    secrets:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

  whitespace-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore BopVisualEffects.sln -p:SkipGameReferences=true

      - name: Verify whitespace formatting
        run: dotnet format whitespace BopVisualEffects.sln --no-restore --verify-no-changes --verbosity minimal --exclude BopVisualEffects/obj

  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore BopVisualEffects.sln -p:SkipGameReferences=true

      - name: Verify code style rules
        run: dotnet format style BopVisualEffects.sln --no-restore --verify-no-changes --verbosity minimal --exclude BopVisualEffects/obj

  analyzers:
    needs: setup-game-dlls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Download game DLLs artifact
        uses: actions/download-artifact@v4
        with:
          name: game-dlls
          path: ~/bits-and-bops/Bits & Bops_Data/Managed

      - name: Create BopVisualEffects.user.props
        run: |
          mkdir -p BopVisualEffects
          cat > BopVisualEffects/BopVisualEffects.user.props << EOF
          <Project>
            <PropertyGroup>
              <GameRoot>$HOME/bits-and-bops</GameRoot>
            </PropertyGroup>
          </Project>
          EOF

      - name: Restore
        run: dotnet restore BopVisualEffects.sln

      - name: Verify analyzer rules
        run: dotnet format analyzers BopVisualEffects.sln --no-restore --verify-no-changes --verbosity minimal --exclude BopVisualEffects/obj
